application: theinternetparty
version: 0-99

runtime: python27
api_version: 1
threadsafe: false


handlers:
    
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
   
- url: /static/
  static_dir: static


### CONSOLE ###

- url: /console/static
  static_dir: console/app/view/static  
  
- url: /console.*
  script: console/app/console.py
  login: admin

- url: /.*
  script: main.py 
  
  

builtins:
  - remote_api: on
  - appstats: on
  - deferred: on 

inbound_services:
  - xmpp_message
  - mail
  - channel_presence

